# Generated by Django 5.2.3 on 2025-06-19 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicants', '0002_alter_application_applicant_alter_application_job'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='applications',
            field=models.ManyToManyField(related_name='job_applications', through='applicants.Application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
