# Generated by Django 5.2.3 on 2025-06-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COMPANY', 'Company'), ('JOBSEEKER', 'Job Seeker')], default='JOBSEEKER', max_length=50),
        ),
    ]
