# Generated by Django 5.2.3 on 2025-06-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('EMPLOYER', 'Company'), ('JOBSEEKER', 'Job Seeker')], default='JOBSEEKER', max_length=50),
        ),
    ]
